### ISSUE TITLE
`items` are cleared if another input changes (e.g. `thumbs`)

### ISSUE THREAD

**Issue by pappkamerad** [daelmaak/ngx-gallery#102]
when another gallery input, like `thumbs` is changed after `items` is already set, this line here clears all items, resulting in nothing to be shown.
https://github.com/daelmaak/ngx-gallery/blob/master/libs/gallery/src/lib/components/gallery/gallery.component.ts#L197

**Comment by daelmaak** [comment]
Thanks, will have a look 🙈
