### ISSUE TITLE
When `items` switches from 0 to more than 1 image, the last one is shown initially, not the first one

### ISSUE THREAD

**Issue by pappkamerad** [daelmaak/ngx-gallery#104]
i assume, it is due to `center()` not being called after inputs changed (https://github.com/daelmaak/ngx-gallery/blob/master/libs/gallery/src/lib/components/viewer/viewer.component.ts#L274)

my workaround currently is to call `gallery.select(0)` after we updated the `items` but this slides the images once :(

**Comment by daelmaak** [comment]
Thanks. I wrote a [test](https://github.com/daelmaak/ngx-gallery/blob/master/libs/gallery/src/lib/components/viewer/viewer.component.cy.ts#L32) and created a [repo ](https://stackblitz.com/edit/ngx-gallery-demo-responsive-xuzh9y?file=package.json,src%2Fapp%2Fapp.component.ts) to reproduce it but no success. Can you please elaborate or create a reproduction stackblitz?

**Comment by daelmaak** [comment]
I reproduced it in `loop` mode 👍
