### ISSUE TITLE
Cannot find module @daelmakk/ngx-gallery

### ISSUE THREAD

**Issue by ViktorDimitrievski** [daelmaak/ngx-gallery#108]
Hello Daniel,

The Gallery is awesome and I have used for 2-3months. Last 2 days I'm having issue with it. It's not possible to include the component in the project. I have created new angular project and try to include the Gallery but I got an issue that is not found. I have tried couple of different versions of importing.Everything that I was thinking that is going to solve the issue I have tried by my self....no success. So I'm sending few screenshots and errors of the issue. I hope you can help me and others if have same issue. 
Thank you!

'gallery' is not a known element:
1. If 'gallery' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
![image (1)](https://github.com/user-attachments/assets/53369c3c-b487-4881-9ed2-04f5c180454a)

![image (2)](https://github.com/user-attachments/assets/d818329c-3e92-4f9a-b8ee-45382f1bd48d)

**Comment by daelmaak** [comment]
Thanks for the issue @ViktorDimitrievski , it was my fault of publishing wrong file structure. It's already fixed in 3.1.1.
