### ISSUE TITLE
Aria label for interactable elements

### ISSUE THREAD

**Issue by witnessthefitness** [daelmaak/ngx-gallery#39]
currently there is no possibility to add aria labels to previous and next buttons in the gallery and the thumbs.
please provide a property for the aria object respectively.

**Comment by daelmaak** [comment]
I don't see the need to provide custom aria labels atm, but I provided default ones for now https://github.com/daelmaak/ngx-gallery/pull/87. 

I am actually still not sure if gallery should provide much a11y assistance given it's primarily visual tool, which is probably of not much use to visually impaired people.
